

transactionMode: OMID
#transactionMode: HBASE
#transactionMode: AJITTS

#create HBase tables of TPC-E
createTables: false

#parse file or load serialized data
loadFromXML: false

#load serialized trace file if exists
loadFromSerialized: true

loadPath: files/serialized/

filesList:
  - testeMini.dat

allTypeTransactions: false

allowedTransactions:
  - TRADE_UPDATE
  - DATA_MAINTENANCE
  - MARKET_FEED
  - TRADE_RESULT
  - TRADE_ORDER

replicateTrace: 1
intervalBetweenReplicate: 0


threadPool: 35

