
#to-do warm
# if false run only with HBase
transactions: true

#create HBase tables of TPC-E
createTables: false

#parse file or load serialized data
loadFromXML: false

#load serialized trace file if exists
loadFromSerialized: true

loadPath: files/serialized/

filesList:
  - binlog_1.dat

allTypeTransactions: false

allowedTransactions:
  - TRADE_UPDATE
  - DATA_MAINTENANCE
  - MARKET_FEED
  - TRADE_RESULT
  - TRADE_ORDER



threadPool: 35

