

transactionMode: OMID
#transactionMode: HBASE
#transactionMode: AJITTS

#create HBase tables of TPC-E
createTables: false

#parse file or load serialized data
loadFromXML: false

#load serialized trace file if exists
loadFromSerialized: true

loadPath: files/serialized/

filesList:
  - binlog_1.dat
  - binlog_12.dat
  - binlog_3.dat
  - binlog_4.dat
  - binlog_5.dat
  - binlog_6.dat
  - binlog_7.dat
  - binlog_8.dat
  - binlog_9.dat
  - binlog_10.dat
  - binlog_11.dat
  - binlog_12.dat
  - binlog_13.dat
  - binlog_14.dat
  - binlog_15.dat
  - binlog_16.dat

allTypeTransactions: false

allowedTransactions:
  - TRADE_UPDATE
  - DATA_MAINTENANCE
  - MARKET_FEED
  - TRADE_RESULT
  - TRADE_ORDER

replicateTrace: 1
intervalBetweenReplicate: 0


threadPool: 35

